server:
  address: ${HOST:127.0.0.1}
  port: ${PORT:4310}

spring:
  datasource:
    url: jdbc:h2:mem:ai-note;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
